name: 'Magento 2 quick integration tests'
author: 'ExtDN'
description: 'runs quick integration tests for given Magento 2 open source version'
inputs:
  module_name:
    description: 'Your Magento module name. Example: Foo_Bar'
    required: true
  composer_name:
    description: 'Your composer name. Example: foo/magento2-bar'
    required: true
  ce_version:
    description: 'Magento 2 Open Source version number'
    required: true
    default: '2.3.5'
  module_source:
    description: 'Relative path to your module source within your repository. Empty by default.'
  phpunit_file:
    description: 'Relative path to your own PHPUnit file. Leave empty to use the default.'
  magento_pre_install_script:
    description: 'Relative path to an optional script before Magento installation is run. Leave empty to use the default.'
runs:
  using: 'docker'
  image: 'docker://yireo/github-actions-magento-quick-integration-tests:latest'
branding:
  icon: 'code'  
  color: 'green'

