name: Example workflow
on: [push, pull_request]

jobs:
  example:
    name: Example job
    runs-on: ubuntu-latest
    env:
        foobar: "example2"
    steps:
      - uses: actions/checkout@v2
      - uses: yireo-training/YireoTraining_ExampleGithubWorkflows/.github/actions/example@master
        with:
          foobar: "example1"
