name: PHPStan
on: [push, pull_request]

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    env:
        foobar: "example2"
    steps:
      - uses: actions/checkout@v2
      - uses: yireo-training/YireoTraining_ExampleGithubWorkflows/.github/actions/magento-phpstan@master
        with:
          composer_name: ${{ secrets.COMPOSER_NAME }}
          foobar: "example1"
