name: ExtDN M2 PHPStan
on: [push, pull_request]

jobs:
  phpstan:
    name: M2 PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: yireo-training/YireoTraining_ExampleGithubWorkflows/.github/actions/magento-phpstan@master
        with:
          composer_name: ${{ secrets.COMPOSER_NAME }}
